### ISSUE TITLE
In my application, I am getting the data from server. So how will I use this library as the row count is zero before getting data. Please help me.

### ISSUE THREAD

**Issue by reenaphilip** [samhann/Loader.swift#13]

**Comment by GitMAM** [comment]
Before you get the data from server you can call 
        Loader.addLoaderToViews([self.tableview])
and in the completion handler after you successfully get your data call 
        Loader.removeLoaderFromViews([self.tableview])

If you don't have a completion handler you can just do like this : 

       Loader.addLoaderToViews([self.tableview])
        self.posts = ImagePost.fetchPosts(viewController: self, queryLimit: page)
        Loader.removeLoaderFromViews([self.tableview])

**Comment by celikomer** [comment]
When I do this I get the gradient as one single view over my tableview. Any other way to fix the issue?

**Comment by reenaphilip** [comment]
@GitMAM : Sorry for the late response. I implemented it as you explained. Added before service call and removed once the response received. Its working.
